### ISSUE TITLE
no such file to load -- rack/handler

### ISSUE THREAD

**Issue by jkutner** [trinidad/trinidad_init_services#14] opened 2012-02-16 21:10 UTC
I'm encountering this error on a server that used to work:

```
JRubyDaemon: Script raised an error: org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- rack/handler
org.jruby.exceptions.RaiseException: (LoadError) no such file to load -- rack/handler
at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1038)
at Kernel.require(/opt/jruby/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:36)
at #<Class:0x38d0357a>.(root)(/opt/jruby-1.6.5/lib/ruby/gems/1.8/gems/trinidad-1.3.3/lib/rack/handler/trinidad.rb:1)
at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1038)
at Kernel.require(/opt/jruby-1.6.5/lib/ruby/gems/1.8/gems/trinidad-1.3.3/lib/rack/handler/trinidad.rb:36)
at #<Class:0x38d0357a>.(root)(/opt/jruby-1.6.5/lib/ruby/gems/1.8/gems/trinidad-1.3.3/lib/trinidad.rb:21)
at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:1038)
at Kernel.require(/opt/jruby-1.6.5/lib/ruby/gems/1.8/gems/trinidad-1.3.3/lib/trinidad.rb:59)
at opt.jruby_minus_1_dot_6_dot_5.lib.ruby.gems.$1_dot_8.gems.trinidad_init_services_minus_1_dot_1_dot_2.lib.trinidad_init_services.(root)(/opt/jruby-1.6.5/lib/ruby/gems/1.8/gems/trinidad_init_services-1.1.2/lib/trinidad_init_services.rb:2)
 Cannot load daemon
```

Installing rack manually fixed this.  The rack gem is a development dependency of Trinidad proper, but I think it needs to be a runtime dependency of either trinidad_init_services or trinidad.

**Comment by calavera** [comment] 2012-02-16 21:15
Actually it's not a dependency, jruby-rack loads rack. The problem is that Rack now uses autoload and when trinidad tries to load rack/handler nothing has been already loaded by rack yet. I'm not completely sure if requiring rack we fix the problem

**Comment by jkutner** [comment] 2012-02-16 21:21
i don't mean require it.  I mean add this to the trinidad_init_services gemspec:

```
s.add_dependency('rack')
```

it wasn't even installed for me.  that seems weird though... wouldn't it have been installed if there is a dependency on trinidad -> jruby-rack -> rack

**Comment by calavera** [comment] 2012-02-16 21:29
it doesn't need to be installed, jruby-rack bundles it.

**Comment by jkutner** [comment] 2012-02-16 22:23
i see. so is it bad for me to `gem install rack` as a workaround?

**Comment by calavera** [comment] 2012-02-17 00:20
ohh I think this issue is duplicated, check this out:

https://github.com/trinidad/trinidad/issues/48

I'm closing it

**Closed as completed by calavera** 2012-02-17 00:20 UTC
